cycling_uk_application_process.add_form:
  title: 'Add cycling uk application process'
  route_name: entity.cycling_uk_application_process.add_form
  appears_on:
    - entity.cycling_uk_application_process.collection
