services:
  cycling_uk_application_process.event_subscriber:
    class: Drupal\cycling_uk_application_process\EventSubscriber\CyclingUkApplicationProcessSubscriber
    arguments: ['@entity_type.manager']
    tags:
      - { name: event_subscriber }
